## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('simple-point-to-point-olsr-ipv6',
                                 ['point-to-point', 'internet', 'ipv6-olsr', 'applications', 'wifi'])
    obj.source = 'simple-point-to-point-olsr-ipv6.cc'

    obj = bld.create_ns3_program('olsr-hna-ipv6',
                                 ['core', 'mobility', 'wifi', 'csma', 'ipv6-olsr'])
    obj.source = 'olsr-hna-ipv6.cc'
